name: Unity-Ftp-Deploy

on:
  push:
    branches:
      - develop # developブランチにpushされた時
      - master # masterブランチにpushされた時

jobs:
  develop-deploy:
    if: github.ref == 'refs/heads/develop'
    name: Develop Deploy
    runs-on: ubuntu-latest
    environment: 
      name: prd 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: ${{ secrets.FTP_SERVER_DIR_DEV }}

  master-deploy:
    if: github.ref == 'refs/heads/master'
    name: Master Deploy
    runs-on: ubuntu-latest
    environment: 
      name: prd 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./src/
          server-dir: ${{ secrets.FTP_SERVER_DIR_PRD }}