name: FTP Deploy

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    environment: 
      name: prd  #環境名を指定（記載しないとSecretを取得不可）

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Return String
      run: echo secret "${{secrets.FTP_SERVER }}" | sed 's/./& /g'

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./src/ # デプロイするディレクトリを指定
        server-dir: ./web/dev/ # リモートのディレクトリを指定
